### PR TITLE
add-octocat-png

### PR DESCRIPTION
**Pull request by mendonk**

### CODE REVIEW

**Comment by mendonk** [comment]
@cbornet I can't get the svg or png logos to appear correctly, sorry. Any suggestions?

**Comment by cbornet** [comment]
Is it possible to add it as a font-awesome icon ? https://fontawesome.com/icons/github

**Comment by cbornet** [comment]
I couldn't make it work. GitBook doesn't look like an OSS solution. Are we sure we want to use it ?

**Comment by cbornet** [comment]
I also tried by adding an image but it doesn't seem to work in the SUMMARY.

**Comment by cbornet** [comment]
This is from LangChain's doc:
image

But maybe they're not using GitBook.com (they don't have the "Powered by GitBook" banner)

**Comment by mendonk** [comment]
They are using [Docusaurus](https://docusaurus.io/) - I'll look into it

**Comment by mendonk** [comment]
GitBook restricts this action

**Pull request closed without merging**
