### PR TITLE
Add sequence diagrams for custom agents

### PR DESCRIPTION
**Pull request by cbornet**

### CODE REVIEW

**Comment by cbornet** [comment]
Arf! It seems Gitbook doesn't support mermaid...

**Comment by cbornet** [comment]
@mendonk can we add mermaid’s integration to GitBook ?

**Comment by mendonk** [comment]
@cbornet Mermaid is now added

**Comment by cbornet** [comment]
Thanks. It works.
Preview here: https://docs.langstream.ai/~/revisions/kTWSUGHk8s5mHRFdb84R/pipeline-agents/agent-developer-guide/agent-creation#creating-agents

**Comment by mendonk** [comment]
This looks great! Thanks @cbornet !

**Pull request merged**
